#!/bin/bash
GET_IP_URL="https://api.ipify.org/"
UPDATE_SCRIPT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/update
LOGGER_SCRIPT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/log
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/config

HOST_RESULT="$(host $freenom_domain_name 80.80.80.80)"
DNS_IP=$(echo $HOST_RESULT | cut -d' ' -f 12)
CURR_IP="$(curl -s $GET_IP_URL)"

$LOGGER_SCRIPT start

$LOGGER_SCRIPT continue "Current IP: $CURR_IP :: DNS IP: $DNS_IP"

if [ $DNS_IP = $CURR_IP ]
then
$LOGGER_SCRIPT continue "No change is needed, exiting"
else
$LOGGER_SCRIPT continue "Change is needed procedeing to execute freenom update script"
$UPDATE_SCRIPT
fi
$LOGGER_SCRIPT end